global using Basket;
global using Catalog;
global using Ordering;
global using Serilog;
global using Carter;
global using Shared.Exceptions.Handlers;
global using Shared.Extentions;
global using FluentValidation;
global using Shared.Behaviors;